spring.application.name=spring-ai-mcp-app

server.port=9206

#Open AI Configuration using Docker
spring.ai.openai.base-url=http://localhost:12434/v1
spring.ai.openai.api-key=docker
#spring.ai.openai.chat.options.model=ai/smollm2:135M-Q4_K_M
spring.ai.openai.chat.options.model=ai/qwen2.5:3B-Q4_K_M

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

#MCP Server Configuration
spring.ai.mcp.client.stdio.servers-configuration=classpath:servers.json

logging.level.org.springframework.ai.mcp=DEBUG
logging.level.io.modelcontextprotocol=DEBUG
logging.level.org.springframework.ai.tool=DEBUG


#spring.ai.openai.api-key=${OPENAI_API_KEY} 
### Because we are using free api token https://console.groq.com  ->OpenAi is not free
#spring.ai.openai.base-url=https://api.groq.com/openai
#spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
