spring.application.name=help-desk-backend

server.port=9206

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_ai_helpdesk
spring.datasource.username=postgres
spring.datasource.password=root

#spring.datasource.url=jdbc:postgresql://localhost:5433/spring_ai_project
#spring.datasource.username=r
#spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.ai.openai.api-key=${OPENAI_API_KEY} 

## Because we are using free api token https://console.groq.com  ->OpenAi is not free
#spring.ai.openai.base-url=https://api.groq.com/openai/v1
#spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

#spring.ai.openai.base-url=http://localhost:12434/engines
spring.ai.openai.base-url=http://localhost:12434/v1
spring.ai.openai.api-key=docker
spring.ai.openai.chat.options.model=ai/qwen2.5:3B-Q4_K_M 

logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.ai.chat.memory.repository.jdbc.initialize-schema=ALWAYS