spring.application.name=textsummarizer

server.port=9207

# Gemini
spring.ai.google.genai.api-key=AQ.Ab8RN6LezOGahUPao4N84kz28BY-ohmH5XESZCK8LtEW0Lu2oA
spring.ai.google.genai.chat.options.model=gemini-2.0-flash-exp

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/text_summarizer
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver