spring.application.name=textsummarizer

server.port=9207

# Gemini					   
spring.ai.google.genai.api-key=AQ.Ab8RN6LB2yQ7cEbkbcH6I4aM6TrwCByN008VL1QkZ-MbCUlvWA
spring.ai.google.genai.chat.options.model=gemini-flash-latest

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/text_summarizer
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

## Hibernate Dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#
## Format SQL
#spring.jpa.properties.hibernate.format_sql=true
#
## Pretty-print SQL in logs (optional)
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

