spring.application.name=dockerModelExample

#Open AI Configuration
spring.ai.openai.base-url=http://localhost:12434/engines
spring.ai.openai.api-key=docker
spring.ai.openai.chat.options.model=ai/smollm2:135M-Q4_K_M