spring.application.name=chatClientApi

server.port=9204

#add in Run->Run Configurations->Environment->Variable =Value in STS
spring.ai.openai.api-key=${OPENAI_API_KEY} 

## Because we are using free api token https://console.groq.com  ->OpenAi is not free
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile


#Ollama Configuration
#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.options.model=codellama:latest
#spring.ai.ollama.chat.options.temperature=0.7


#when we want to run multiple chatModel then use below propertiy
#spring.ai.chat.client.enabled=false

#Add simple Logger Properties
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_ai_project
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.ai.chat.memory.repository.jdbc.initialize-schema=ALWAYS