spring.application.name=chatbot-moniter

server.port=9206

# Expose all actuator endpoints
management.endpoints.web.exposure.include=*

# (Optional) Show health details
management.endpoint.health.show-details=always

#add in Run->Run Configurations->Environment->Variable =Value in STS
#spring.ai.openai.api-key=${OPENAI_API_KEY} 
#
### Because we are using free api token https://console.groq.com  ->OpenAi is not free
#spring.ai.openai.base-url=https://api.groq.com/openai
#spring.ai.openai.chat.options.model=llama-3.3-70b-versatile


spring.ai.openai.base-url=http://localhost:12434/v1
spring.ai.openai.api-key=docker
spring.ai.openai.chat.options.model=ai/qwen2.5:3B-Q4_K_M 

logging.level.org.springframework.ai.chat.client.advisor=DEBUG
