spring.application.name=spring-google-gemini

server.port=9206

#Gemini Ai API Key-Need Biling google api-Key
spring.ai.google.genai.api-key=${GOOGLE_KEY} 
spring.ai.google.genai.chat.options.model=gemini-2.5-pro
#spirng.ai.google.genai.chat.options.model=gemini-3-pro-preview